### ISSUE TITLE
Umbraco UI Form not working after upgrade

### ISSUE THREAD

**Issue by HugoBecerra** [umbraco/Umbraco.UI#583]
### Which *exact* UI Library version are you using? For example: 1.0.1 - don't just write v1.

1.3.0

### Bug summary

I have two simple forms in two custom dashboards. Both of them stop working after installing the version 11.4.2 from version 11.2.1. Now when it loads I get the following error: 

> Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "uui-modal-sidebar" has already been used with this registry
    at https://cdn.jsdelivr.net/npm/@umbraco-ui/uui@latest/dist/uui.min.js:187:64
    at https://cdn.jsdelivr.net/npm/@umbraco-ui/uui@latest/dist/uui.min.js:187:79
    at ts (https://cdn.jsdelivr.net/npm/@umbraco-ui/uui@latest/dist/uui.min.js:272:10690)
    at https://cdn.jsdelivr.net/npm/@umbraco-ui/uui@latest/dist/uui.min.js:272:12779
    at https://cdn.jsdelivr.net/npm/@umbraco-ui/uui@latest/dist/uui.min.js:1:178
    at https://cdn.jsdelivr.net/npm/@umbraco-ui/uui@latest/dist/uui.min.js:1:193

### Steps to reproduce

- Add a custom dashboard in Umbraco 12.4.2
- Try to add the JS for UUI 1.3.0. 
- Run and open the dashboard.
- Check the console and look for the error.

**Comment by iOvergaard** [comment]
Hi @HugoBecerra 
It should not be necessary for you to add UUI manually to the backoffice through a CDN, since UUI is already included with Umbraco. You are getting this error because two different installations of the UI library is trying to register the same component. It should work if you remove any references to https://cdn.jsdelivr.net/npm/@umbraco-ui/uui@latest/dist/uui.min.js

Let me know how it goes.
