### ISSUE TITLE
Incorrect link from readme to component in Storybook

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.UI#599]
### Which *exact* UI Library version are you using? For example: 1.0.1 - don't just write v1.

1.5.0

### Bug summary

While looking through readme I noticed they have link to component on Storybook, e.g.
https://uui.umbraco.com/?path=/story/uui-box

but this is invalid

![image](https://github.com/umbraco/Umbraco.UI/assets/2919859/bfbcb27d-cf77-42b1-a93d-6a13b0df71d5)

it seems it should be this instead:
https://uui.umbraco.com/?path=/docs/uui-box--docs

Furthermore I noticed a `uui-boolean-input` component here:
https://github.com/umbraco/Umbraco.UI/blob/v1/contrib/packages/uui-boolean-input/README.md

but I can't find this component here: https://uui.umbraco.com/

### Steps to reproduce

Check link in readme for each component linking to Storybook.

**Comment by iOvergaard** [comment]
Hi @bjarnef 
You are right about the backlinks from the readme. Looks like Storybook changed the URL format at some point.

Regarding uui-boolean-input, we purposely did not create a story for it since it is an abstract component only meant to be extended. It is exported as an abstract class with Typescript and it is also not registered as a custom element, so everything is good here, but thanks for your concerns!
